#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 190

#define TAP_CODE_DELAY 10

#define PERMISSIVE_HOLD

#define COMBO_TERM 40

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define MOUSEKEY_INERTIA
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 64
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 32
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 24
#undef MOUSEKEY_FRICTION
#define MOUSEKEY_FRICTION 24
#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA 1
