#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 190
#define FLOW_TAP_TERM 140
#define COMBO_TERM 40

#define TAP_CODE_DELAY 10
#define PERMISSIVE_HOLD

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define MOUSEKEY_INERTIA
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 36
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 34
#undef MOUSEKEY_FRICTION
#define MOUSEKEY_FRICTION 26
#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA 1
